-- Seed: Minna no Nihongo — Bài 7-12 (từ vựng)
-- Nguồn: PDF Minato Dorimu, đối chiếu + sửa lỗi theo danh mục từ vựng MNN chuẩn
-- Quy tắc: word = kana (+ chú thích sách), reading = CHỈ kana + ～, kanji = kanji (NULL nếu không có)
-- site_id: 1219bda2-aa1e-4288-ab7e-caff011cdf5c

DO $$
DECLARE
  sid uuid := '1219bda2-aa1e-4288-ab7e-caff011cdf5c';
  l7 uuid; l8 uuid; l9 uuid; l10 uuid; l11 uuid; l12 uuid;
BEGIN
SELECT id INTO l7  FROM mnn_lessons WHERE site_id = sid AND lesson_number = 7;
SELECT id INTO l8  FROM mnn_lessons WHERE site_id = sid AND lesson_number = 8;
SELECT id INTO l9  FROM mnn_lessons WHERE site_id = sid AND lesson_number = 9;
SELECT id INTO l10 FROM mnn_lessons WHERE site_id = sid AND lesson_number = 10;
SELECT id INTO l11 FROM mnn_lessons WHERE site_id = sid AND lesson_number = 11;
SELECT id INTO l12 FROM mnn_lessons WHERE site_id = sid AND lesson_number = 12;

IF l7 IS NULL OR l8 IS NULL OR l9 IS NULL OR l10 IS NULL OR l11 IS NULL OR l12 IS NULL THEN
  RAISE EXCEPTION 'mnn_lessons 7-12 chưa tồn tại cho site %', sid;
END IF;

-- ════════════════════════════════════════
-- BÀI 7 — xóa và seed lại (48 từ)
-- ════════════════════════════════════════
DELETE FROM mnn_vocabulary WHERE lesson_id = l7;
INSERT INTO mnn_vocabulary (site_id, lesson_id, word, reading, romanization, meaning_vi, part_of_speech, order_index, kanji) VALUES
  (sid, l7, 'きります',             'きります',             'kirimasu',                'cắt',                                                              '動詞',    1,  '切ります'),
  (sid, l7, 'おくります',           'おくります',           'okurimasu',               'gửi',                                                              '動詞',    2,  '送ります'),
  (sid, l7, 'あげます',             'あげます',             'agemasu',                 'cho, tặng',                                                        '動詞',    3,  NULL),
  (sid, l7, 'もらいます',           'もらいます',           'moraimasu',               'nhận',                                                             '動詞',    4,  NULL),
  (sid, l7, 'かします',             'かします',             'kashimasu',               'cho mượn, cho vay',                                                '動詞',    5,  '貸します'),
  (sid, l7, 'かります',             'かります',             'karimasu',                'mượn, vay',                                                        '動詞',    6,  '借ります'),
  (sid, l7, 'おしえます',           'おしえます',           'oshiemasu',               'dạy',                                                              '動詞',    7,  '教えます'),
  (sid, l7, 'ならいます',           'ならいます',           'naraimasu',               'học (từ người khác)',                                              '動詞',    8,  '習います'),
  (sid, l7, 'かけます',             'かけます',             'kakemasu',                'gọi (điện thoại)',                                                 '動詞',    9,  NULL),
  (sid, l7, 'て',                   'て',                   'te',                      'tay',                                                              '名詞',    10, '手'),
  (sid, l7, 'はし',                 'はし',                 'hashi',                   'đũa',                                                              '名詞',    11, NULL),
  (sid, l7, 'スプーン',             'スプーン',             'supuun',                  'muỗng, thìa',                                                      '名詞',    12, NULL),
  (sid, l7, 'ナイフ',               'ナイフ',               'naifu',                   'con dao',                                                          '名詞',    13, NULL),
  (sid, l7, 'フォーク',             'フォーク',             'fooku',                   'nĩa, dĩa',                                                         '名詞',    14, NULL),
  (sid, l7, 'はさみ',               'はさみ',               'hasami',                  'cái kéo',                                                          '名詞',    15, NULL),
  (sid, l7, 'ファクス',             'ファクス',             'fakusu',                  'máy fax',                                                          '名詞',    16, NULL),
  (sid, l7, 'ワープロ',             'ワープロ',             'waapuro',                 'máy đánh chữ, máy xử lý văn bản',                                  '名詞',    17, NULL),
  (sid, l7, 'パソコン',             'パソコン',             'pasokon',                 'máy tính (cá nhân)',                                               '名詞',    18, NULL),
  (sid, l7, 'パンチ',               'パンチ',               'panchi',                  'cái đục lỗ (giấy)',                                                '名詞',    19, NULL),
  (sid, l7, 'ホッチキス',           'ホッチキス',           'hotchikisu',              'cái dập ghim, cái bấm kim',                                        '名詞',    20, NULL),
  (sid, l7, 'セロテープ',           'セロテープ',           'seroteepu',               'băng keo, băng dính',                                              '名詞',    21, NULL),
  (sid, l7, 'けしゴム',             'けしゴム',             'keshigomu',               'cục tẩy, cái tẩy',                                                 '名詞',    22, '消しゴム'),
  (sid, l7, 'かみ',                 'かみ',                 'kami',                    'giấy',                                                             '名詞',    23, '紙'),
  (sid, l7, 'はな',                 'はな',                 'hana',                    'hoa',                                                              '名詞',    24, '花'),
  (sid, l7, 'シャツ',               'シャツ',               'shatsu',                  'áo sơ mi',                                                         '名詞',    25, NULL),
  (sid, l7, 'プレゼント',           'プレゼント',           'purezento',               'quà tặng',                                                         '名詞',    26, NULL),
  (sid, l7, 'にもつ',               'にもつ',               'nimotsu',                 'hành lý, đồ đạc',                                                  '名詞',    27, '荷物'),
  (sid, l7, 'おかね',               'おかね',               'okane',                   'tiền',                                                             '名詞',    28, 'お金'),
  (sid, l7, 'きっぷ',               'きっぷ',               'kippu',                   'vé (tàu, xe)',                                                     '名詞',    29, '切符'),
  (sid, l7, 'クリスマス',           'クリスマス',           'kurisumasu',              'Giáng sinh, Nô-en',                                                '名詞',    30, NULL),
  (sid, l7, 'ちち',                 'ちち',                 'chichi',                  'bố (của mình)',                                                    '名詞',    31, '父'),
  (sid, l7, 'はは',                 'はは',                 'haha',                    'mẹ (của mình)',                                                    '名詞',    32, '母'),
  (sid, l7, 'おとうさん',           'おとうさん',           'otousan',                 'bố (của người khác)',                                              '名詞',    33, 'お父さん'),
  (sid, l7, 'おかあさん',           'おかあさん',           'okaasan',                 'mẹ (của người khác)',                                              '名詞',    34, 'お母さん'),
  (sid, l7, 'もう',                 'もう',                 'mou',                     'đã ~ rồi',                                                         '副詞',    35, NULL),
  (sid, l7, 'まだ',                 'まだ',                 'mada',                    'chưa, vẫn chưa',                                                   '副詞',    36, NULL),
  (sid, l7, 'これから',             'これから',             'korekara',                'từ bây giờ, sau đây',                                              '副詞',    37, NULL),
  (sid, l7, '～すてきですね',       '～すてきですね',       '~ suteki desu ne',        '~ đẹp quá nhỉ, hay quá nhỉ (khen ngợi)',                           '表現',    38, NULL),
  (sid, l7, 'ごめんください',       'ごめんください',       'gomen kudasai',           'Xin lỗi, có ai ở nhà không? (gọi khi đến nhà người khác)',         '挨拶',    39, NULL),
  (sid, l7, 'いらっしゃい',         'いらっしゃい',         'irasshai',                'xin mời, chào mừng (nói với khách đến nhà)',                       '挨拶',    40, NULL),
  (sid, l7, 'どうぞおあがりください', 'どうぞおあがりください', 'douzo oagari kudasai',  'Mời anh/chị vào nhà',                                              '表現',    41, 'どうぞお上がりください'),
  (sid, l7, 'しつれいします',       'しつれいします',       'shitsurei shimasu',       'Xin phép, tôi xin thất lễ (khi vào nhà người khác)',               '挨拶',    42, '失礼します'),
  (sid, l7, '～は いかがですか',    '～はいかがですか',     '~ wa ikaga desu ka',      'Anh/chị dùng ~ có được không? (mời ăn uống)',                      '表現',    43, NULL),
  (sid, l7, 'いただきます',         'いただきます',         'itadakimasu',             'Tôi xin phép (nói trước khi ăn, uống)',                            '挨拶',    44, NULL),
  (sid, l7, 'りょこう',             'りょこう',             'ryokou',                  'du lịch, chuyến du lịch (～をします: đi du lịch)',                 '名詞',    45, '旅行'),
  (sid, l7, 'おみやげ',             'おみやげ',             'omiyage',                 'quà, quà lưu niệm',                                                '名詞',    46, 'お土産'),
  (sid, l7, 'ヨーロッパ',           'ヨーロッパ',           'Yooroppa',                'châu Âu',                                                          '固有名詞', 47, NULL),
  (sid, l7, 'スペイン',             'スペイン',             'Supein',                  'Tây Ban Nha',                                                      '固有名詞', 48, NULL);

-- ════════════════════════════════════════
-- BÀI 8 — xóa và seed lại (55 từ: 52 PDF + tách 暑い/熱い + 2 bổ sung)
-- ════════════════════════════════════════
DELETE FROM mnn_vocabulary WHERE lesson_id = l8;
INSERT INTO mnn_vocabulary (site_id, lesson_id, word, reading, romanization, meaning_vi, part_of_speech, order_index, kanji) VALUES
  (sid, l8, 'ハンサム[な]',         'ハンサム',             'hansamu [na]',            'đẹp trai',                                                         'な形容詞', 1,  NULL),
  (sid, l8, 'きれい[な]',           'きれい',               'kirei [na]',              'đẹp, sạch, sạch sẽ',                                               'な形容詞', 2,  NULL),
  (sid, l8, 'しずか[な]',           'しずか',               'shizuka [na]',            'yên tĩnh',                                                         'な形容詞', 3,  '静か[な]'),
  (sid, l8, 'にぎやか[な]',         'にぎやか',             'nigiyaka [na]',           'náo nhiệt, nhộn nhịp',                                             'な形容詞', 4,  NULL),
  (sid, l8, 'ゆうめい[な]',         'ゆうめい',             'yuumei [na]',             'nổi tiếng',                                                        'な形容詞', 5,  '有名[な]'),
  (sid, l8, 'しんせつ[な]',         'しんせつ',             'shinsetsu [na]',          'tốt bụng, thân thiện',                                             'な形容詞', 6,  '親切[な]'),
  (sid, l8, 'げんき[な]',           'げんき',               'genki [na]',              'khỏe, khỏe mạnh',                                                  'な形容詞', 7,  '元気[な]'),
  (sid, l8, 'ひま[な]',             'ひま',                 'hima [na]',               'rảnh, rảnh rỗi',                                                   'な形容詞', 8,  '暇[な]'),
  (sid, l8, 'べんり[な]',           'べんり',               'benri [na]',              'tiện lợi, thuận tiện',                                             'な形容詞', 9,  '便利[な]'),
  (sid, l8, 'すてき[な]',           'すてき',               'suteki [na]',             'đẹp, hay, tuyệt vời',                                              'な形容詞', 10, NULL),
  (sid, l8, 'おおきい',             'おおきい',             'ookii',                   'to, lớn',                                                          'い形容詞', 11, '大きい'),
  (sid, l8, 'ちいさい',             'ちいさい',             'chiisai',                 'nhỏ, bé',                                                          'い形容詞', 12, '小さい'),
  (sid, l8, 'あたらしい',           'あたらしい',           'atarashii',               'mới',                                                              'い形容詞', 13, '新しい'),
  (sid, l8, 'ふるい',               'ふるい',               'furui',                   'cũ',                                                               'い形容詞', 14, '古い'),
  (sid, l8, 'いい',                 'いい',                 'ii',                      'tốt',                                                              'い形容詞', 15, NULL),
  (sid, l8, 'わるい',               'わるい',               'warui',                   'xấu',                                                              'い形容詞', 16, '悪い'),
  (sid, l8, 'あつい',               'あつい',               'atsui',                   'nóng (thời tiết)',                                                 'い形容詞', 17, '暑い'),
  (sid, l8, 'あつい',               'あつい',               'atsui',                   'nóng (đồ vật, khi chạm vào)',                                      'い形容詞', 18, '熱い'),
  (sid, l8, 'つめたい',             'つめたい',             'tsumetai',                'lạnh (cảm giác khi chạm vào)',                                     'い形容詞', 19, '冷たい'),
  (sid, l8, 'さむい',               'さむい',               'samui',                   'lạnh (thời tiết)',                                                 'い形容詞', 20, '寒い'),
  (sid, l8, 'むずかしい',           'むずかしい',           'muzukashii',              'khó',                                                              'い形容詞', 21, '難しい'),
  (sid, l8, 'やさしい',             'やさしい',             'yasashii',                'dễ',                                                               'い形容詞', 22, '易しい'),
  (sid, l8, 'たかい',               'たかい',               'takai',                   'đắt, cao',                                                         'い形容詞', 23, '高い'),
  (sid, l8, 'やすい',               'やすい',               'yasui',                   'rẻ',                                                               'い形容詞', 24, '安い'),
  (sid, l8, 'ひくい',               'ひくい',               'hikui',                   'thấp',                                                             'い形容詞', 25, '低い'),
  (sid, l8, 'おもしろい',           'おもしろい',           'omoshiroi',               'thú vị, hay',                                                      'い形容詞', 26, NULL),
  (sid, l8, 'おいしい',             'おいしい',             'oishii',                  'ngon',                                                             'い形容詞', 27, NULL),
  (sid, l8, 'いそがしい',           'いそがしい',           'isogashii',               'bận, bận rộn',                                                     'い形容詞', 28, '忙しい'),
  (sid, l8, 'たのしい',             'たのしい',             'tanoshii',                'vui, vui vẻ',                                                      'い形容詞', 29, '楽しい'),
  (sid, l8, 'しろい',               'しろい',               'shiroi',                  'trắng',                                                            'い形容詞', 30, '白い'),
  (sid, l8, 'くろい',               'くろい',               'kuroi',                   'đen',                                                              'い形容詞', 31, '黒い'),
  (sid, l8, 'あかい',               'あかい',               'akai',                    'đỏ',                                                               'い形容詞', 32, '赤い'),
  (sid, l8, 'あおい',               'あおい',               'aoi',                     'xanh, xanh da trời',                                               'い形容詞', 33, '青い'),
  (sid, l8, 'さくら',               'さくら',               'sakura',                  'hoa anh đào',                                                      '名詞',    34, '桜'),
  (sid, l8, 'やま',                 'やま',                 'yama',                    'núi',                                                              '名詞',    35, '山'),
  (sid, l8, 'まち',                 'まち',                 'machi',                   'thành phố, thị trấn, khu phố',                                     '名詞',    36, '町'),
  (sid, l8, 'たべもの',             'たべもの',             'tabemono',                'thức ăn, đồ ăn',                                                   '名詞',    37, '食べ物'),
  (sid, l8, 'くるま',               'くるま',               'kuruma',                  'xe ô tô, xe hơi',                                                  '名詞',    38, '車'),
  (sid, l8, 'ところ',               'ところ',               'tokoro',                  'chỗ, nơi',                                                         '名詞',    39, '所'),
  (sid, l8, 'りょう',               'りょう',               'ryou',                    'ký túc xá',                                                        '名詞',    40, '寮'),
  (sid, l8, 'べんきょう',           'べんきょう',           'benkyou',                 'sự học, việc học (～をします: học)',                               '名詞',    41, '勉強'),
  (sid, l8, 'せいかつ',             'せいかつ',             'seikatsu',                'cuộc sống, sinh hoạt',                                             '名詞',    42, '生活'),
  (sid, l8, '[お]しごと',           'おしごと',             '[o]shigoto',              'công việc (～をします: làm việc)',                                 '名詞',    43, '[お]仕事'),
  (sid, l8, 'どう',                 'どう',                 'dou',                     'thế nào',                                                          '疑問詞',  44, NULL),
  (sid, l8, 'どんな',               'どんな',               'donna',                   '~ như thế nào, ~ nào (đứng trước danh từ)',                        '疑問詞',  45, NULL),
  (sid, l8, 'どれ',                 'どれ',                 'dore',                    'cái nào (trong 3 thứ trở lên)',                                    '疑問詞',  46, NULL),
  (sid, l8, 'とても',               'とても',               'totemo',                  'rất, lắm',                                                         '副詞',    47, NULL),
  (sid, l8, 'あまり',               'あまり',               'amari',                   'không ~ lắm (dùng với phủ định)',                                  '副詞',    48, NULL),
  (sid, l8, 'そして',               'そして',               'soshite',                 'và, thêm nữa (nối câu)',                                           '接続詞',  49, NULL),
  (sid, l8, '～が、～',             '～が～',               '~ ga ~',                  '~ nhưng ~ (nối hai vế câu)',                                       '助詞',    50, NULL),
  (sid, l8, 'おげんきですか',       'おげんきですか',       'ogenki desu ka',          'Anh/chị có khỏe không?',                                           '挨拶',    51, 'お元気ですか'),
  (sid, l8, 'そうですね',           'そうですね',           'sou desu ne',             'đúng vậy nhỉ (thể hiện sự đồng tình)',                             '表現',    52, NULL),
  (sid, l8, 'シャンハイ',           'シャンハイ',           'Shanhai',                 'Thượng Hải',                                                       '固有名詞', 53, NULL),
  (sid, l8, 'そろそろしつれいします', 'そろそろしつれいします', 'sorosoro shitsurei shimasu', 'Đến lúc tôi phải xin phép về (chào trước khi ra về)',         '表現',    54, 'そろそろ失礼します'), -- bổ sung ngoài PDF
  (sid, l8, 'またいらっしゃってください', 'またいらっしゃってください', 'mata irasshatte kudasai', 'Mời anh/chị lại đến chơi',                              '表現',    55, NULL); -- bổ sung ngoài PDF

-- ════════════════════════════════════════
-- BÀI 9 — xóa và seed lại (53 từ: 50 PDF + tách 夫/主人, 妻/家内, 早く/速く)
-- ════════════════════════════════════════
DELETE FROM mnn_vocabulary WHERE lesson_id = l9;
INSERT INTO mnn_vocabulary (site_id, lesson_id, word, reading, romanization, meaning_vi, part_of_speech, order_index, kanji) VALUES
  (sid, l9, 'わかります',           'わかります',           'wakarimasu',              'hiểu, nắm được',                                                   '動詞',    1,  '分かります'),
  (sid, l9, 'あります',             'あります',             'arimasu',                 'có (sở hữu)',                                                      '動詞',    2,  NULL),
  (sid, l9, 'すき[な]',             'すき',                 'suki [na]',               'thích',                                                            'な形容詞', 3,  '好き[な]'),
  (sid, l9, 'きらい[な]',           'きらい',               'kirai [na]',              'ghét, không thích',                                                'な形容詞', 4,  '嫌い[な]'),
  (sid, l9, 'じょうず[な]',         'じょうず',             'jouzu [na]',              'giỏi, khéo',                                                       'な形容詞', 5,  '上手[な]'),
  (sid, l9, 'へた[な]',             'へた',                 'heta [na]',               'kém, vụng',                                                        'な形容詞', 6,  '下手[な]'),
  (sid, l9, 'りょうり',             'りょうり',             'ryouri',                  'món ăn, việc nấu ăn (～をします: nấu ăn)',                         '名詞',    7,  '料理'),
  (sid, l9, 'のみもの',             'のみもの',             'nomimono',                'đồ uống',                                                          '名詞',    8,  '飲み物'),
  (sid, l9, 'スポーツ',             'スポーツ',             'supootsu',                'thể thao (～をします: chơi thể thao)',                             '名詞',    9,  NULL),
  (sid, l9, 'やきゅう',             'やきゅう',             'yakyuu',                  'bóng chày (～をします: chơi bóng chày)',                           '名詞',    10, '野球'),
  (sid, l9, 'ダンス',               'ダンス',               'dansu',                   'nhảy, khiêu vũ (～をします: nhảy, khiêu vũ)',                      '名詞',    11, NULL),
  (sid, l9, 'おんがく',             'おんがく',             'ongaku',                  'âm nhạc',                                                          '名詞',    12, '音楽'),
  (sid, l9, 'うた',                 'うた',                 'uta',                     'bài hát',                                                          '名詞',    13, '歌'),
  (sid, l9, 'クラシック',           'クラシック',           'kurashikku',              'nhạc cổ điển',                                                     '名詞',    14, NULL),
  (sid, l9, 'ジャズ',               'ジャズ',               'jazu',                    'nhạc jazz',                                                        '名詞',    15, NULL),
  (sid, l9, 'コンサート',           'コンサート',           'konsaato',                'buổi hòa nhạc',                                                    '名詞',    16, NULL),
  (sid, l9, 'カラオケ',             'カラオケ',             'karaoke',                 'karaoke',                                                          '名詞',    17, NULL),
  (sid, l9, 'かぶき',               'かぶき',               'kabuki',                  'kabuki (một loại ca kịch truyền thống của Nhật)',                  '名詞',    18, '歌舞伎'),
  (sid, l9, 'え',                   'え',                   'e',                       'tranh, hội họa',                                                   '名詞',    19, '絵'),
  (sid, l9, 'じ',                   'じ',                   'ji',                      'chữ',                                                              '名詞',    20, '字'),
  (sid, l9, 'かんじ',               'かんじ',               'kanji',                   'chữ Hán',                                                          '名詞',    21, '漢字'),
  (sid, l9, 'ひらがな',             'ひらがな',             'hiragana',                'chữ hiragana',                                                     '名詞',    22, NULL),
  (sid, l9, 'かたかな',             'かたかな',             'katakana',                'chữ katakana',                                                     '名詞',    23, NULL),
  (sid, l9, 'ローマじ',             'ローマじ',             'roomaji',                 'chữ La Mã (romaji)',                                               '名詞',    24, 'ローマ字'),
  (sid, l9, 'こまかいおかね',       'こまかいおかね',       'komakai okane',           'tiền lẻ',                                                          '名詞',    25, '細かいお金'),
  (sid, l9, 'チケット',             'チケット',             'chiketto',                'vé (xem hòa nhạc, xem phim)',                                      '名詞',    26, NULL),
  (sid, l9, 'じかん',               'じかん',               'jikan',                   'thời gian',                                                        '名詞',    27, '時間'),
  (sid, l9, 'ようじ',               'ようじ',               'youji',                   'việc bận, công chuyện',                                            '名詞',    28, '用事'),
  (sid, l9, 'やくそく',             'やくそく',             'yakusoku',                'cuộc hẹn, lời hứa',                                                '名詞',    29, '約束'),
  (sid, l9, 'ごしゅじん',           'ごしゅじん',           'goshujin',                'chồng (chồng của người khác)',                                     '名詞',    30, 'ご主人'),
  (sid, l9, 'おっと',               'おっと',               'otto',                    'chồng (chồng mình)',                                               '名詞',    31, '夫'),
  (sid, l9, 'しゅじん',             'しゅじん',             'shujin',                  'chồng (chồng mình, cách nói khác)',                                '名詞',    32, '主人'),
  (sid, l9, 'おくさん',             'おくさん',             'okusan',                  'vợ (vợ của người khác)',                                           '名詞',    33, '奥さん'),
  (sid, l9, 'つま',                 'つま',                 'tsuma',                   'vợ (vợ mình)',                                                     '名詞',    34, '妻'),
  (sid, l9, 'かない',               'かない',               'kanai',                   'vợ (vợ mình, cách nói khiêm nhường)',                              '名詞',    35, '家内'),
  (sid, l9, 'こども',               'こども',               'kodomo',                  'con, con cái, trẻ em',                                             '名詞',    36, '子ども'),
  (sid, l9, 'よく',                 'よく',                 'yoku',                    'rõ, tốt (chỉ mức độ: よくわかります — hiểu rõ)',                   '副詞',    37, NULL),
  (sid, l9, 'だいたい',             'だいたい',             'daitai',                  'đại khái, đại thể, phần lớn',                                      '副詞',    38, NULL),
  (sid, l9, 'たくさん',             'たくさん',             'takusan',                 'nhiều',                                                            '副詞',    39, NULL),
  (sid, l9, 'すこし',               'すこし',               'sukoshi',                 'ít, một chút',                                                     '副詞',    40, '少し'),
  (sid, l9, 'ぜんぜん',             'ぜんぜん',             'zenzen',                  'hoàn toàn ~ không (đi với phủ định)',                              '副詞',    41, '全然'),
  (sid, l9, 'はやく',               'はやく',               'hayaku',                  'sớm',                                                              '副詞',    42, '早く'),
  (sid, l9, 'はやく',               'はやく',               'hayaku',                  'nhanh',                                                            '副詞',    43, '速く'),
  (sid, l9, '～から',               '～から',               '~ kara',                  'vì ~ (chỉ lý do)',                                                 '助詞',    44, NULL),
  (sid, l9, 'どうして',             'どうして',             'doushite',                'tại sao, vì sao',                                                  '疑問詞',  45, NULL),
  (sid, l9, 'ざんねんです[ね]',     'ざんねんですね',       'zannen desu [ne]',        'thật đáng tiếc (nhỉ), buồn nhỉ',                                   '表現',    46, '残念です[ね]'),
  (sid, l9, 'すみません',           'すみません',           'sumimasen',               'xin lỗi',                                                          '表現',    47, NULL),
  (sid, l9, 'もしもし',             'もしもし',             'moshimoshi',              'a-lô (khi gọi điện thoại)',                                        '感動詞',  48, NULL),
  (sid, l9, 'ああ',                 'ああ',                 'aa',                      'a, à (khi đã gặp được đúng người trên điện thoại)',                '感動詞',  49, NULL),
  (sid, l9, 'いっしょにいかがですか', 'いっしょにいかがですか', 'issho ni ikaga desu ka', 'Anh/chị cùng ~ (làm gì đó) với chúng tôi được không?',            '表現',    50, NULL),
  (sid, l9, '[～は]ちょっと…',      '～はちょっと',         '[~ wa] chotto...',        '[~ thì] có lẽ không được rồi (cách từ chối khéo một lời mời)',     '表現',    51, NULL),
  (sid, l9, 'だめですか',           'だめですか',           'dame desu ka',            'Không được à?',                                                    '表現',    52, NULL),
  (sid, l9, 'またこんどおねがいします', 'またこんどおねがいします', 'mata kondo onegai shimasu', 'hẹn lần sau vậy (đáp khéo khi bị từ chối lời mời)',       '表現',    53, NULL);

-- ════════════════════════════════════════
-- BÀI 10 — xóa và seed lại (47 từ)
-- ════════════════════════════════════════
DELETE FROM mnn_vocabulary WHERE lesson_id = l10;
INSERT INTO mnn_vocabulary (site_id, lesson_id, word, reading, romanization, meaning_vi, part_of_speech, order_index, kanji) VALUES
  (sid, l10, 'います',              'います',               'imasu',                   'có, ở (tồn tại — dùng cho người và động vật)',                     '動詞',    1,  NULL),
  (sid, l10, 'あります',            'あります',             'arimasu',                 'có (tồn tại — dùng cho đồ vật)',                                   '動詞',    2,  NULL),
  (sid, l10, 'いろいろ[な]',        'いろいろ',             'iroiro [na]',             'nhiều, đa dạng',                                                   'な形容詞', 3,  NULL),
  (sid, l10, 'おとこのひと',        'おとこのひと',         'otoko no hito',           'người đàn ông',                                                    '名詞',    4,  '男の人'),
  (sid, l10, 'おんなのひと',        'おんなのひと',         'onna no hito',            'người đàn bà, phụ nữ',                                             '名詞',    5,  '女の人'),
  (sid, l10, 'おとこのこ',          'おとこのこ',           'otoko no ko',             'cậu con trai, bé trai',                                            '名詞',    6,  '男の子'),
  (sid, l10, 'おんなのこ',          'おんなのこ',           'onna no ko',              'cô con gái, bé gái',                                               '名詞',    7,  '女の子'),
  (sid, l10, 'いぬ',                'いぬ',                 'inu',                     'chó',                                                              '名詞',    8,  '犬'),
  (sid, l10, 'ねこ',                'ねこ',                 'neko',                    'mèo',                                                              '名詞',    9,  '猫'),
  (sid, l10, 'き',                  'き',                   'ki',                      'cây, gỗ',                                                          '名詞',    10, '木'),
  (sid, l10, 'もの',                'もの',                 'mono',                    'vật, đồ vật',                                                      '名詞',    11, '物'),
  (sid, l10, 'フィルム',            'フィルム',             'firumu',                  'phim (cuộn phim máy ảnh)',                                         '名詞',    12, NULL),
  (sid, l10, 'でんち',              'でんち',               'denchi',                  'pin',                                                              '名詞',    13, '電池'),
  (sid, l10, 'はこ',                'はこ',                 'hako',                    'hộp',                                                              '名詞',    14, '箱'),
  (sid, l10, 'スイッチ',            'スイッチ',             'suitchi',                 'công tắc',                                                         '名詞',    15, NULL),
  (sid, l10, 'れいぞうこ',          'れいぞうこ',           'reizouko',                'tủ lạnh',                                                          '名詞',    16, '冷蔵庫'),
  (sid, l10, 'テーブル',            'テーブル',             'teeburu',                 'bàn',                                                              '名詞',    17, NULL),
  (sid, l10, 'ベッド',              'ベッド',               'beddo',                   'giường',                                                           '名詞',    18, NULL),
  (sid, l10, 'たな',                'たな',                 'tana',                    'giá, kệ (đựng đồ, sách)',                                          '名詞',    19, '棚'),
  (sid, l10, 'ドア',                'ドア',                 'doa',                     'cửa',                                                              '名詞',    20, NULL),
  (sid, l10, 'まど',                'まど',                 'mado',                    'cửa sổ',                                                           '名詞',    21, '窓'),
  (sid, l10, 'ポスト',              'ポスト',               'posuto',                  'hộp thư, hòm thư',                                                 '名詞',    22, NULL),
  (sid, l10, 'ビル',                'ビル',                 'biru',                    'tòa nhà',                                                          '名詞',    23, NULL),
  (sid, l10, 'こうえん',            'こうえん',             'kouen',                   'công viên',                                                        '名詞',    24, '公園'),
  (sid, l10, 'きっさてん',          'きっさてん',           'kissaten',                'quán giải khát, quán cà phê',                                      '名詞',    25, '喫茶店'),
  (sid, l10, 'ほんや',              'ほんや',               'hon''ya',                 'hiệu sách',                                                        '名詞',    26, '本屋'),
  (sid, l10, '～や',                '～や',                 '~ ya',                    'hiệu ~, cửa hàng ~',                                               '接尾辞',  27, '～屋'),
  (sid, l10, 'のりば',              'のりば',               'noriba',                  'bến xe, điểm lên xuống (xe, tàu)',                                 '名詞',    28, '乗り場'),
  (sid, l10, 'けん',                'けん',                 'ken',                     'tỉnh',                                                             '名詞',    29, '県'),
  (sid, l10, 'うえ',                'うえ',                 'ue',                      'trên, phía trên',                                                  '名詞',    30, '上'),
  (sid, l10, 'した',                'した',                 'shita',                   'dưới, phía dưới',                                                  '名詞',    31, '下'),
  (sid, l10, 'まえ',                'まえ',                 'mae',                     'trước, phía trước',                                                '名詞',    32, '前'),
  (sid, l10, 'うしろ',              'うしろ',               'ushiro',                  'sau, phía sau',                                                    '名詞',    33, '後ろ'),
  (sid, l10, 'みぎ',                'みぎ',                 'migi',                    'phải, bên phải',                                                   '名詞',    34, '右'),
  (sid, l10, 'ひだり',              'ひだり',               'hidari',                  'trái, bên trái',                                                   '名詞',    35, '左'),
  (sid, l10, 'なか',                'なか',                 'naka',                    'trong, bên trong, giữa',                                           '名詞',    36, '中'),
  (sid, l10, 'そと',                'そと',                 'soto',                    'ngoài, bên ngoài',                                                 '名詞',    37, '外'),
  (sid, l10, 'となり',              'となり',               'tonari',                  'bên cạnh',                                                         '名詞',    38, '隣'),
  (sid, l10, 'ちかく',              'ちかく',               'chikaku',                 'gần, vùng lân cận',                                                '名詞',    39, '近く'),
  (sid, l10, 'あいだ',              'あいだ',               'aida',                    'giữa (khoảng giữa hai vật)',                                       '名詞',    40, '間'),
  (sid, l10, '～や～[など]',        '～や～など',           '~ ya ~ [nado]',           '~ và ~ (liệt kê không hết), [v.v.]',                               '助詞',    41, NULL),
  (sid, l10, 'いちばん～',          'いちばん～',           'ichiban ~',               'nhất, ~ nhất (いちばんうえ: trên cùng, cao nhất)',                 '副詞',    42, NULL),
  (sid, l10, '～だんめ',            '～だんめ',             '~ danme',                 'ngăn thứ ~, tầng thứ ~ (だん dùng để đếm ngăn của giá, kệ v.v.)',  '接尾辞',  43, '～段目'),
  (sid, l10, '[どうも]すみません',  'どうもすみません',     '[doumo] sumimasen',       'cảm ơn (khi làm phiền ai đó giúp mình)',                           '表現',    44, NULL),
  (sid, l10, 'チリソース',          'チリソース',           'chirisoosu',              'tương ớt (chili sauce)',                                           '名詞',    45, NULL),
  (sid, l10, 'おく',                'おく',                 'oku',                     'bên trong cùng, phía trong cùng',                                  '名詞',    46, '奥'),
  (sid, l10, 'スパイス',            'スパイス',             'supaisu',                 'gia vị',                                                           '名詞',    47, NULL);

-- ════════════════════════════════════════
-- BÀI 11 — xóa và seed lại (57 từ: 56 PDF + tách カレー/カレーライス)
-- ════════════════════════════════════════
DELETE FROM mnn_vocabulary WHERE lesson_id = l11;
INSERT INTO mnn_vocabulary (site_id, lesson_id, word, reading, romanization, meaning_vi, part_of_speech, order_index, kanji) VALUES
  (sid, l11, 'います',              'います',               'imasu',                   'có (con)',                                                         '動詞',    1,  NULL),
  (sid, l11, 'います',              'います',               'imasu',                   'ở (Nhật Bản)',                                                     '動詞',    2,  NULL),
  (sid, l11, 'かかります',          'かかります',           'kakarimasu',              'mất, tốn (thời gian, tiền bạc)',                                   '動詞',    3,  NULL),
  (sid, l11, 'やすみます',          'やすみます',           'yasumimasu',              'nghỉ, nghỉ ngơi',                                                  '動詞',    4,  '休みます'),
  (sid, l11, 'ひとつ',              'ひとつ',               'hitotsu',                 '1 cái (đếm đồ vật)',                                               '名詞',    5,  NULL),
  (sid, l11, 'ふたつ',              'ふたつ',               'futatsu',                 '2 cái',                                                            '名詞',    6,  NULL),
  (sid, l11, 'みっつ',              'みっつ',               'mittsu',                  '3 cái',                                                            '名詞',    7,  NULL),
  (sid, l11, 'よっつ',              'よっつ',               'yottsu',                  '4 cái',                                                            '名詞',    8,  NULL),
  (sid, l11, 'いつつ',              'いつつ',               'itsutsu',                 '5 cái',                                                            '名詞',    9,  NULL),
  (sid, l11, 'むっつ',              'むっつ',               'muttsu',                  '6 cái',                                                            '名詞',    10, NULL),
  (sid, l11, 'ななつ',              'ななつ',               'nanatsu',                 '7 cái',                                                            '名詞',    11, NULL),
  (sid, l11, 'やっつ',              'やっつ',               'yattsu',                  '8 cái',                                                            '名詞',    12, NULL),
  (sid, l11, 'ここのつ',            'ここのつ',             'kokonotsu',               '9 cái',                                                            '名詞',    13, NULL),
  (sid, l11, 'とお',                'とお',                 'too',                     '10 cái',                                                           '名詞',    14, NULL),
  (sid, l11, 'いくつ',              'いくつ',               'ikutsu',                  'bao nhiêu cái',                                                    '疑問詞',  15, NULL),
  (sid, l11, 'ひとり',              'ひとり',               'hitori',                  '1 người',                                                          '名詞',    16, '一人'),
  (sid, l11, 'ふたり',              'ふたり',               'futari',                  '2 người',                                                          '名詞',    17, '二人'),
  (sid, l11, '～にん',              '～にん',               '~ nin',                   '~ người (đếm người, từ 3 người trở lên)',                          '接尾辞',  18, '～人'),
  (sid, l11, '～だい',              '～だい',               '~ dai',                   '~ cái, chiếc (đếm máy móc, xe cộ)',                                '接尾辞',  19, '～台'),
  (sid, l11, '～まい',              '～まい',               '~ mai',                   '~ tờ, tấm (đếm vật mỏng như áo, giấy…)',                           '接尾辞',  20, '～枚'),
  (sid, l11, '～かい',              '～かい',               '~ kai',                   '~ lần',                                                            '接尾辞',  21, '～回'),
  (sid, l11, 'りんご',              'りんご',               'ringo',                   'quả táo',                                                          '名詞',    22, NULL),
  (sid, l11, 'みかん',              'みかん',               'mikan',                   'quả quýt',                                                         '名詞',    23, NULL),
  (sid, l11, 'サンドイッチ',        'サンドイッチ',         'sandoitchi',              'bánh sandwich',                                                    '名詞',    24, NULL),
  (sid, l11, 'カレー',              'カレー',               'karee',                   'món cà ri',                                                        '名詞',    25, NULL),
  (sid, l11, 'カレーライス',        'カレーライス',         'karee raisu',             'cơm cà ri',                                                        '名詞',    26, NULL),
  (sid, l11, 'アイスクリーム',      'アイスクリーム',       'aisukuriimu',             'kem',                                                              '名詞',    27, NULL),
  (sid, l11, 'きって',              'きって',               'kitte',                   'tem, con tem',                                                     '名詞',    28, '切手'),
  (sid, l11, 'はがき',              'はがき',               'hagaki',                  'bưu thiếp',                                                        '名詞',    29, NULL),
  (sid, l11, 'ふうとう',            'ふうとう',             'fuutou',                  'phong bì',                                                         '名詞',    30, '封筒'),
  (sid, l11, 'そくたつ',            'そくたつ',             'sokutatsu',               'chuyển phát nhanh',                                                '名詞',    31, '速達'),
  (sid, l11, 'かきとめ',            'かきとめ',             'kakitome',                'thư bảo đảm, gửi bảo đảm',                                         '名詞',    32, '書留'),
  (sid, l11, 'エアメール',          'エアメール',           'eameeru',                 'thư (gửi bằng) đường hàng không',                                  '名詞',    33, NULL),
  (sid, l11, 'ふなびん',            'ふなびん',             'funabin',                 'thư gửi bằng đường biển',                                          '名詞',    34, '船便'),
  (sid, l11, 'りょうしん',          'りょうしん',           'ryoushin',                'bố mẹ, cha mẹ',                                                    '名詞',    35, '両親'),
  (sid, l11, 'きょうだい',          'きょうだい',           'kyoudai',                 'anh chị em',                                                       '名詞',    36, '兄弟'),
  (sid, l11, 'あに',                'あに',                 'ani',                     'anh trai (của mình)',                                              '名詞',    37, '兄'),
  (sid, l11, 'おにいさん',          'おにいさん',           'oniisan',                 'anh trai (của người khác)',                                        '名詞',    38, 'お兄さん'),
  (sid, l11, 'あね',                'あね',                 'ane',                     'chị gái (của mình)',                                               '名詞',    39, '姉'),
  (sid, l11, 'おねえさん',          'おねえさん',           'oneesan',                 'chị gái (của người khác)',                                         '名詞',    40, 'お姉さん'),
  (sid, l11, 'おとうと',            'おとうと',             'otouto',                  'em trai (của mình)',                                               '名詞',    41, '弟'),
  (sid, l11, 'おとうとさん',        'おとうとさん',         'otoutosan',               'em trai (của người khác)',                                         '名詞',    42, '弟さん'),
  (sid, l11, 'いもうと',            'いもうと',             'imouto',                  'em gái (của mình)',                                                '名詞',    43, '妹'),
  (sid, l11, 'いもうとさん',        'いもうとさん',         'imoutosan',               'em gái (của người khác)',                                          '名詞',    44, '妹さん'),
  (sid, l11, 'がいこく',            'がいこく',             'gaikoku',                 'nước ngoài',                                                       '名詞',    45, '外国'),
  (sid, l11, '～じかん',            '～じかん',             '~ jikan',                 '~ tiếng, ~ giờ (khoảng thời gian)',                                '接尾辞',  46, '～時間'),
  (sid, l11, '～しゅうかん',        '～しゅうかん',         '~ shuukan',               '~ tuần',                                                           '接尾辞',  47, '～週間'),
  (sid, l11, '～かげつ',            '～かげつ',             '~ kagetsu',               '~ tháng',                                                          '接尾辞',  48, '～か月'),
  (sid, l11, '～ねん',              '～ねん',               '~ nen',                   '~ năm',                                                            '接尾辞',  49, '～年'),
  (sid, l11, '～ぐらい',            '～ぐらい',             '~ gurai',                 'khoảng ~',                                                         '助詞',    50, NULL),
  (sid, l11, 'どのくらい',          'どのくらい',           'dono kurai',              'bao lâu, khoảng bao nhiêu',                                        '疑問詞',  51, NULL),
  (sid, l11, 'ぜんぶで',            'ぜんぶで',             'zenbu de',                'tổng cộng, tất cả',                                                '副詞',    52, '全部で'),
  (sid, l11, 'みんな',              'みんな',               'minna',                   'mọi người, tất cả',                                                '名詞',    53, NULL),
  (sid, l11, '～だけ',              '～だけ',               '~ dake',                  'chỉ ~',                                                            '助詞',    54, NULL),
  (sid, l11, 'いらっしゃいませ',    'いらっしゃいませ',     'irasshaimase',            'xin mời quý khách (câu chào của nhân viên cửa hàng)',              '挨拶',    55, NULL),
  (sid, l11, 'それから',            'それから',             'sorekara',                'sau đó, thêm nữa (dùng khi gọi thêm món)',                         '接続詞',  56, NULL),
  (sid, l11, 'オーストラリア',      'オーストラリア',       'Oosutoraria',             'Úc, Australia',                                                    '固有名詞', 57, NULL);

-- ════════════════════════════════════════
-- BÀI 12 — xóa và seed lại (49 từ: 47 PDF + tách 速い/早い, 暖かい/温かい)
-- ════════════════════════════════════════
DELETE FROM mnn_vocabulary WHERE lesson_id = l12;
INSERT INTO mnn_vocabulary (site_id, lesson_id, word, reading, romanization, meaning_vi, part_of_speech, order_index, kanji) VALUES
  (sid, l12, 'かんたん[な]',        'かんたん',             'kantan [na]',             'đơn giản, dễ',                                                     'な形容詞', 1,  '簡単[な]'),
  (sid, l12, 'ちかい',              'ちかい',               'chikai',                  'gần',                                                              'い形容詞', 2,  '近い'),
  (sid, l12, 'とおい',              'とおい',               'tooi',                    'xa',                                                               'い形容詞', 3,  '遠い'),
  (sid, l12, 'はやい',              'はやい',               'hayai',                   'nhanh',                                                            'い形容詞', 4,  '速い'),
  (sid, l12, 'はやい',              'はやい',               'hayai',                   'sớm',                                                              'い形容詞', 5,  '早い'),
  (sid, l12, 'おそい',              'おそい',               'osoi',                    'chậm, muộn',                                                       'い形容詞', 6,  '遅い'),
  (sid, l12, 'おおい [ひとが～]',   'おおい',               'ooi [hito ga ~]',         'nhiều [người]',                                                    'い形容詞', 7,  '多い [人が～]'),
  (sid, l12, 'すくない [ひとが～]', 'すくない',             'sukunai [hito ga ~]',     'ít [người]',                                                       'い形容詞', 8,  '少ない [人が～]'),
  (sid, l12, 'あたたかい',          'あたたかい',           'atatakai',                'ấm (thời tiết)',                                                   'い形容詞', 9,  '暖かい'),
  (sid, l12, 'あたたかい',          'あたたかい',           'atatakai',                'ấm, nóng (đồ ăn, đồ uống, đồ vật)',                                'い形容詞', 10, '温かい'),
  (sid, l12, 'すずしい',            'すずしい',             'suzushii',                'mát, mát mẻ',                                                      'い形容詞', 11, '涼しい'),
  (sid, l12, 'あまい',              'あまい',               'amai',                    'ngọt',                                                             'い形容詞', 12, '甘い'),
  (sid, l12, 'からい',              'からい',               'karai',                   'cay',                                                              'い形容詞', 13, '辛い'),
  (sid, l12, 'おもい',              'おもい',               'omoi',                    'nặng',                                                             'い形容詞', 14, '重い'),
  (sid, l12, 'かるい',              'かるい',               'karui',                   'nhẹ',                                                              'い形容詞', 15, '軽い'),
  (sid, l12, 'いい [コーヒーが～]', 'いい',                 'ii [koohii ga ~]',        'chọn, dùng [cà phê] (dùng khi gọi, chọn món)',                     'い形容詞', 16, NULL),
  (sid, l12, 'きせつ',              'きせつ',               'kisetsu',                 'mùa',                                                              '名詞',    17, '季節'),
  (sid, l12, 'はる',                'はる',                 'haru',                    'mùa xuân',                                                         '名詞',    18, '春'),
  (sid, l12, 'なつ',                'なつ',                 'natsu',                   'mùa hè',                                                           '名詞',    19, '夏'),
  (sid, l12, 'あき',                'あき',                 'aki',                     'mùa thu',                                                          '名詞',    20, '秋'),
  (sid, l12, 'ふゆ',                'ふゆ',                 'fuyu',                    'mùa đông',                                                         '名詞',    21, '冬'),
  (sid, l12, 'てんき',              'てんき',               'tenki',                   'thời tiết',                                                        '名詞',    22, '天気'),
  (sid, l12, 'あめ',                'あめ',                 'ame',                     'mưa',                                                              '名詞',    23, '雨'),
  (sid, l12, 'ゆき',                'ゆき',                 'yuki',                    'tuyết',                                                            '名詞',    24, '雪'),
  (sid, l12, 'くもり',              'くもり',               'kumori',                  'có mây, trời râm',                                                 '名詞',    25, '曇り'),
  (sid, l12, 'ホテル',              'ホテル',               'hoteru',                  'khách sạn',                                                        '名詞',    26, NULL),
  (sid, l12, 'くうこう',            'くうこう',             'kuukou',                  'sân bay',                                                          '名詞',    27, '空港'),
  (sid, l12, 'うみ',                'うみ',                 'umi',                     'biển, đại dương',                                                  '名詞',    28, '海'),
  (sid, l12, 'せかい',              'せかい',               'sekai',                   'thế giới',                                                         '名詞',    29, '世界'),
  (sid, l12, 'パーティー',          'パーティー',           'paatii',                  'tiệc (～をします: tổ chức tiệc)',                                  '名詞',    30, NULL),
  (sid, l12, '[お]まつり',          'おまつり',             '[o]matsuri',              'lễ hội',                                                           '名詞',    31, '[お]祭り'),
  (sid, l12, 'しけん',              'しけん',               'shiken',                  'kỳ thi, bài thi',                                                  '名詞',    32, '試験'),
  (sid, l12, 'すきやき',            'すきやき',             'sukiyaki',                'sukiyaki (món thịt bò nấu rau)',                                   '名詞',    33, 'すき焼き'),
  (sid, l12, 'さしみ',              'さしみ',               'sashimi',                 'sashimi (món gỏi cá sống)',                                        '名詞',    34, '刺身'),
  (sid, l12, '[お]すし',            'おすし',               '[o]sushi',                'sushi',                                                            '名詞',    35, NULL),
  (sid, l12, 'てんぷら',            'てんぷら',             'tenpura',                 'tempura (món hải sản, rau chiên tẩm bột)',                         '名詞',    36, NULL),
  (sid, l12, 'いけばな',            'いけばな',             'ikebana',                 'nghệ thuật cắm hoa (～をします: cắm hoa)',                         '名詞',    37, '生け花'),
  (sid, l12, 'もみじ',              'もみじ',               'momiji',                  'lá đỏ, lá phong đỏ (mùa thu)',                                     '名詞',    38, '紅葉'),
  (sid, l12, 'どちら',              'どちら',               'dochira',                 'cái nào, bên nào (giữa hai cái)',                                  '疑問詞',  39, NULL),
  (sid, l12, 'はじめて',            'はじめて',             'hajimete',                'lần đầu tiên',                                                     '副詞',    40, '初めて'),
  (sid, l12, 'どちらも',            'どちらも',             'dochira mo',              'cả hai',                                                           '代名詞',  41, NULL),
  (sid, l12, 'ずっと',              'ずっと',               'zutto',                   'hơn hẳn (nhấn mạnh sự khác biệt khi so sánh hai đối tượng)',       '副詞',    42, NULL),
  (sid, l12, 'ただいま',            'ただいま',             'tadaima',                 'Tôi đã về đây (nói khi về đến nhà)',                               '挨拶',    43, NULL),
  (sid, l12, 'おかえりなさい',      'おかえりなさい',       'okaerinasai',             'Anh/chị đã về đấy à (nói với người vừa về đến nhà)',               '挨拶',    44, 'お帰りなさい'),
  (sid, l12, 'すごいですね',        'すごいですね',         'sugoi desu ne',           'Ghê quá nhỉ, hay quá nhỉ (bày tỏ sự thán phục)',                   '表現',    45, NULL),
  (sid, l12, 'でも',                'でも',                 'demo',                    'nhưng',                                                            '接続詞',  46, NULL),
  (sid, l12, 'つかれました',        'つかれました',         'tsukaremashita',          'Tôi mệt rồi',                                                      '表現',    47, '疲れました'),
  (sid, l12, 'ホンコン',            'ホンコン',             'Honkon',                  'Hồng Kông',                                                        '固有名詞', 48, NULL),
  (sid, l12, 'シンガポール',        'シンガポール',         'Shingapooru',             'Singapore',                                                        '固有名詞', 49, NULL);

END $$;
